server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: wishlist

  data:
    mongodb:
      database: wishlist
      uri: mongodb://root:secret@localhost:27017/wishlist?authSource=admin

  redis:
    connection: redis://redis:6379
    host: redis
    port: 6379
    database: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html