spring:
  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE}
  application:
    name: wishlist

  data:
    mongodb:
      database: wishlist
      uri: ${SPRING_MONGO_URI:'mongodb://root:secret@localhost:27017/wishlist?authSource=admin'}

  redis:
    connection: ${SPRING_REDIS_CONNECTION:redis://localhost:6379}
    database: 0

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  endpoint:
    health:
      show-details: always
  health:
    probes:
      enabled: true

springdoc:
  api-docs:
    servers:
      - url: http://localhost:8082
  swagger-ui:
    path: /swagger-ui.html