global:
  scrape_interval: 15s # Intervalo para coleta de métricas

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['nginx:80']
